price_provider: frank_energie
time_resolution: 15

nett_consumption:
  - sensor_type: power_meter
    brand: homewizard
    meter_type: p1
    host: hw-p1-meter

production:
  - sensor_type: power_meter
    brand: homewizard
    meter_type: kwh_3phase
    host: hw-solar

batteries:
  - sensor_type: power_meter
    brand: homewizard
    meter_type: kwh_1phase
    host: hw-batteries
    phase: 3

boilers:
  - sensor_type: power_meter
    brand: homewizard
    meter_type: power_socket
    host: hw-boiler-hot-water
    phase: 3
