price_provider:
  name: Frank Energie
  provider: frank_energie
  time_resolution: 15

sensors:
  nett_consumption:
    name: P1 Meter
    sensor_type: power_meter
    brand: homewizard
    meter_type: p1
    host: hw-p1-meter

  production:
    - name: Solar Panels
      sensor_type: power_meter
      brand: homewizard
      meter_type: kwh_3phase
      host: hw-solar

  storage:
    - name: Batteries
      sensor_type: power_meter
      brand: homewizard
      meter_type: kwh_1phase
      host: hw-batteries
      phase: 3

    - name: Water Heater
      sensor_type: power_meter
      brand: homewizard
      meter_type: power_socket
      host: hw-water-heater
      phase: 3
